# Generated by Django 6.0.3 on 2026-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytaste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(),
        ),
    ]
