# Generated by Django 6.0.3 on 2026-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytaste', '0002_alter_recipe_ingredients_alter_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
